### ISSUE TITLE
Dispatch actions on subscription callback

### ISSUE THREAD

**Issue by tol-is** [ivantsov/redux-subscriber#11]
I needed this library for a side project recently, but in my case, I needed to dispatch an action when the subscription callback is invoked. 

Also because I was using redux-thunk extensively, I would like to have a similar convention where the callback receives via arguments, the dispatcher and state.

Because of that, I didn't want to make a pull request, but if you want to have a look and let me know what you think, I could continue working towards a PR.

https://github.com/tol-is/redux-subscriber

**Comment by ivantsov** [comment]
Hey @tol-is, I'd encourage you to check this issue - https://github.com/ivantsov/redux-subscriber/issues/8. There I explained that dispatching actions inside subscriber callback is not a good idea. That's why I'd like not to support it in the lib.
However, if you have a usecase when you can't overcome this limitation by amending your redux-actions - please share the example and I'll try to help you.
